name: Run Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 30 minutes

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Run script
      run: python remind1hr.py  # Replace with your script name
